repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]  # Ultra-fast Python linter that detects and auto-fixes code issues

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black  # Autoformatter that enforces consistent Python code style

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort  # Automatically sorts and organizes Python imports for readability
